name: Deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
      - master
      - gh-pages

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # don't persist credentials so deploy uses the built-in pages token
          persist-credentials: false

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy-pages:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
